# PowerShell equivalent of seed-data.sh
# Usage: .\seed-data.ps1
# Requires: .env file in repo root (generated by get-keys.ps1)

$ErrorActionPreference = "Stop"
$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$Challenge0  = $ScriptDir
$RepoRoot    = Split-Path -Parent $Challenge0
$EnvFile     = Join-Path $RepoRoot ".env"

# ── Load .env into current process environment ──
if (Test-Path $EnvFile) {
    Get-Content $EnvFile | ForEach-Object {
        # Skip blank / comment lines
        if ($_ -match '^\s*#' -or $_ -match '^\s*$') { return }
        # Parse KEY="VALUE" or KEY=VALUE
        if ($_ -match '^([^=]+)=(.*)$') {
            $key   = $Matches[1].Trim()
            $value = $Matches[2].Trim().Trim('"')
            [System.Environment]::SetEnvironmentVariable($key, $value, "Process")
        }
    }
    Write-Host "Loaded environment variables from $EnvFile" -ForegroundColor Green
} else {
    Write-Host ".env file not found at $EnvFile. Please run get-keys.ps1 first." -ForegroundColor Red
    exit 1
}

Write-Host "Starting data seeding..." -ForegroundColor Cyan

# ── Install Python packages ──
Write-Host "Installing required Python packages..."
pip install azure-cosmos --quiet 2>$null
pip install azure-storage-blob --quiet 2>$null

# ── Create seed_data.py (Cosmos DB seeding) ──
$seedDataPy = Join-Path $Challenge0 "seed_data.py"

@'
import json
import os
from azure.cosmos import CosmosClient, PartitionKey

def load_json_data(file_path):
    data = []
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = json.load(f)
            data = content if isinstance(content, list) else [content]
        print(f"  Loaded {len(data)} records from {file_path}")
        return data
    except Exception as e:
        print(f"  Error loading {file_path}: {e}")
        return []

def setup_cosmos_db():
    print("Setting up Cosmos DB...")
    cosmos_client = CosmosClient(os.environ['COSMOS_ENDPOINT'], os.environ['COSMOS_KEY'])
    database_name = "FactoryOpsDB"
    try:
        database = cosmos_client.create_database_if_not_exists(id=database_name)
        print(f"  Database '{database_name}' ready")
    except Exception as e:
        print(f"  Error creating database: {e}")
        return None, None

    containers_config = {
        'Machines':           {'partition_key': '/type'},
        'Thresholds':         {'partition_key': '/machineType'},
        'Telemetry':          {'partition_key': '/machineId', 'ttl': 2592000},
        'KnowledgeBase':      {'partition_key': '/machineType'},
        'PartsInventory':     {'partition_key': '/category'},
        'Technicians':        {'partition_key': '/department'},
        'WorkOrders':         {'partition_key': '/status'},
        'MaintenanceHistory': {'partition_key': '/machineId'},
        'MaintenanceWindows': {'partition_key': '/isAvailable'},
        'Suppliers':          {'partition_key': '/category'}
    }
    container_clients = {}
    for name, cfg in containers_config.items():
        try:
            c = database.create_container_if_not_exists(
                id=name,
                partition_key=PartitionKey(path=cfg['partition_key']),
                default_ttl=cfg.get('ttl', None)
            )
            container_clients[name] = c
            print(f"  Container '{name}' ready")
        except Exception as e:
            print(f"  Error creating container {name}: {e}")
    return database, container_clients

def seed_cosmos_data(container_clients):
    print("Seeding Cosmos DB data...")
    data_mappings = {
        'Machines':           'data/machines.json',
        'Thresholds':         'data/thresholds.json',
        'Telemetry':          'data/telemetry-samples.json',
        'KnowledgeBase':      'data/knowledge-base.json',
        'PartsInventory':     'data/parts-inventory.json',
        'Technicians':        'data/technicians.json',
        'WorkOrders':         'data/work-orders.json',
        'MaintenanceHistory': 'data/maintenance-history.json',
        'MaintenanceWindows': 'data/maintenance-windows.json',
        'Suppliers':          'data/suppliers.json'
    }
    for container_name, file_path in data_mappings.items():
        if container_name in container_clients:
            data = load_json_data(file_path)
            if data:
                container = container_clients[container_name]
                ok = 0
                for item in data:
                    try:
                        if 'id' not in item:
                            continue
                        container.create_item(body=item)
                        ok += 1
                    except Exception as e:
                        if "Conflict" not in str(e):
                            print(f"  Warning inserting into {container_name}: {e}")
                print(f"  Imported {ok} items into {container_name}")

def main():
    required = ['COSMOS_ENDPOINT', 'COSMOS_KEY']
    missing = [v for v in required if not os.environ.get(v)]
    if missing:
        print(f"  Missing env vars: {', '.join(missing)}")
        return
    _, clients = setup_cosmos_db()
    if clients:
        seed_cosmos_data(clients)
    print("Cosmos DB seeding completed!")

if __name__ == "__main__":
    main()
'@ | Set-Content -Path $seedDataPy -Encoding UTF8

Write-Host "Running Cosmos DB seeding script..."
Push-Location $Challenge0
python $seedDataPy
Pop-Location
Remove-Item $seedDataPy -ErrorAction SilentlyContinue
Write-Host "Cosmos DB seeding complete!" -ForegroundColor Green

# ── Upload kb-wiki markdown files to Blob Storage ──
Write-Host "Uploading kb-wiki markdown files to Blob Storage..." -ForegroundColor Cyan

$seedBlobPy = Join-Path $Challenge0 "seed_blob_wiki.py"

@'
import os, glob
from azure.storage.blob import BlobServiceClient, ContentSettings
from azure.core.exceptions import ResourceExistsError, AzureError

def upload_markdown_files(container_name, folder_path):
    conn = os.environ.get('AZURE_STORAGE_CONNECTION_STRING')
    if not conn:
        raise RuntimeError("Missing AZURE_STORAGE_CONNECTION_STRING in environment.")
    service_client = BlobServiceClient.from_connection_string(conn)
    cc = service_client.get_container_client(container_name)
    try:
        cc.create_container()
        print(f"  Created container '{container_name}'")
    except ResourceExistsError:
        print(f"  Container '{container_name}' already exists")
    except AzureError as e:
        print(f"  Could not create container: {e}")
    files = glob.glob(os.path.join(folder_path, '*.md'))
    if not files:
        print(f"  No markdown files found in {folder_path}")
        return
    cs = ContentSettings(content_type='text/markdown; charset=utf-8')
    uploaded = 0
    for fp in files:
        blob_name = os.path.basename(fp)
        try:
            with open(fp, 'rb') as f:
                cc.upload_blob(name=blob_name, data=f, overwrite=True, content_settings=cs)
            uploaded += 1
            print(f"  Uploaded {blob_name}")
        except Exception as e:
            print(f"  Failed to upload {blob_name}: {e}")
    print(f"  Upload complete: {uploaded} file(s) to '{container_name}'")

if __name__ == '__main__':
    upload_markdown_files('machine-wiki', os.path.join('data', 'kb-wiki'))
'@ | Set-Content -Path $seedBlobPy -Encoding UTF8

Write-Host "Running blob upload script..."
Push-Location $Challenge0
python $seedBlobPy
Pop-Location
Remove-Item $seedBlobPy -ErrorAction SilentlyContinue

# Append COSMOS_DATABASE to .env if not already present
$envContent = Get-Content $EnvFile -Raw
if ($envContent -notmatch 'COSMOS_DATABASE=') {
    Add-Content -Path $EnvFile -Value 'COSMOS_DATABASE="FactoryOpsDB"'
}

Write-Host "Blob upload complete!" -ForegroundColor Green

# ── Seed APIM proxy APIs ──
Write-Host "Seeding API Management (APIM) proxy APIs..." -ForegroundColor Cyan

# Check required vars
$apimRequired = @("AZURE_SUBSCRIPTION_ID", "RESOURCE_GROUP", "APIM_NAME", "COSMOS_ENDPOINT")
$apimMissing = $apimRequired | Where-Object { -not [System.Environment]::GetEnvironmentVariable($_, "Process") }
if ($apimMissing) {
    Write-Host "APIM seeding skipped: missing env var(s): $($apimMissing -join ', ')" -ForegroundColor Yellow
    Write-Host "Done!" -ForegroundColor Green
    exit 0
}

Write-Host "Installing Python packages for APIM..."
pip install azure-identity azure-mgmt-apimanagement==4.0.0 --quiet 2>$null

$seedApimPy = Join-Path $Challenge0 "seed_apim_cosmos_mi.py"

@'
import os
from urllib.parse import urlparse
from azure.identity import AzureCliCredential
from azure.mgmt.apimanagement import ApiManagementClient
from azure.mgmt.apimanagement.models import (
    ApiCreateOrUpdateParameter, OperationContract, ParameterContract,
    Protocol, PolicyContract, ResponseContract,
)

def require_env(name):
    v = os.environ.get(name)
    if not v: raise RuntimeError(f"Missing env: {name}")
    return v

sub_id = require_env("AZURE_SUBSCRIPTION_ID")
rg = require_env("RESOURCE_GROUP")
service = require_env("APIM_NAME")
cosmos_endpoint = require_env("COSMOS_ENDPOINT")

parsed = urlparse(cosmos_endpoint)
cosmos_endpoint = f"{parsed.scheme}://{parsed.hostname}/"
resource_attr = f"{parsed.scheme}://{parsed.hostname}"

def policy_query_all(collection):
    return f"""<policies>
    <inbound>
        <base />
        <set-variable name="requestDateString" value="@(DateTime.UtcNow.ToString(&quot;r&quot;))" />
        <authentication-managed-identity resource="{resource_attr}" output-token-variable-name="msi-access-token" ignore-error="false" />
        <send-request mode="new" response-variable-name="cosmosResponse" timeout="30">
            <set-url>@("{cosmos_endpoint}" + "dbs/FactoryOpsDB/colls/{collection}/docs")</set-url>
            <set-method>POST</set-method>
            <set-header name="Authorization" exists-action="override">
                <value>@("type=aad&amp;ver=1.0&amp;sig=" + (string)context.Variables["msi-access-token"])</value>
            </set-header>
            <set-header name="x-ms-date" exists-action="override">
                <value>@(context.Variables.GetValueOrDefault&lt;string&gt;("requestDateString"))</value>
            </set-header>
            <set-header name="x-ms-version" exists-action="override"><value>2018-12-31</value></set-header>
            <set-header name="x-ms-documentdb-isquery" exists-action="override"><value>true</value></set-header>
            <set-header name="x-ms-documentdb-query-enablecrosspartition" exists-action="override"><value>true</value></set-header>
            <set-header name="Content-Type" exists-action="override"><value>application/query+json</value></set-header>
            <set-header name="Accept" exists-action="override"><value>application/json</value></set-header>
            <set-body>@{{
                return JsonConvert.SerializeObject(new {{
                    query = "SELECT * FROM c",
                    parameters = new object[0]
                }});
            }}</set-body>
        </send-request>
        <choose>
            <when condition="@(((IResponse)context.Variables[&quot;cosmosResponse&quot;]).StatusCode == 200)">
                <return-response>
                    <set-status code="200" reason="OK" />
                    <set-header name="Content-Type" exists-action="override"><value>application/json</value></set-header>
                    <set-body>@{{
                        var response = ((IResponse)context.Variables["cosmosResponse"]).Body.As&lt;JObject&gt;();
                        return response["Documents"].ToString();
                    }}</set-body>
                </return-response>
            </when>
            <otherwise>
                <return-response>
                    <set-status code="502" reason="Cosmos DB Query Failed" />
                    <set-header name="Content-Type" exists-action="override"><value>application/json</value></set-header>
                    <set-body>@{{ return ((IResponse)context.Variables["cosmosResponse"]).Body.As&lt;string&gt;(); }}</set-body>
                </return-response>
            </otherwise>
        </choose>
    </inbound>
    <backend><base /></backend>
    <outbound><base /></outbound>
    <on-error><base /></on-error>
</policies>"""

def policy_query_by_id(collection, param_name, field):
    return f"""<policies>
    <inbound>
        <base />
        <set-variable name="requestDateString" value="@(DateTime.UtcNow.ToString(&quot;r&quot;))" />
        <authentication-managed-identity resource="{resource_attr}" output-token-variable-name="msi-access-token" ignore-error="false" />
        <set-variable name="{param_name}" value="@(context.Request.MatchedParameters[&quot;{param_name}&quot;])" />
        <send-request mode="new" response-variable-name="cosmosResponse" timeout="30">
            <set-url>@("{cosmos_endpoint}" + "dbs/FactoryOpsDB/colls/{collection}/docs")</set-url>
            <set-method>POST</set-method>
            <set-header name="Authorization" exists-action="override">
                <value>@("type=aad&amp;ver=1.0&amp;sig=" + (string)context.Variables["msi-access-token"])</value>
            </set-header>
            <set-header name="x-ms-date" exists-action="override">
                <value>@(context.Variables.GetValueOrDefault&lt;string&gt;("requestDateString"))</value>
            </set-header>
            <set-header name="x-ms-version" exists-action="override"><value>2018-12-31</value></set-header>
            <set-header name="x-ms-documentdb-isquery" exists-action="override"><value>true</value></set-header>
            <set-header name="x-ms-documentdb-query-enablecrosspartition" exists-action="override"><value>true</value></set-header>
            <set-header name="Content-Type" exists-action="override"><value>application/query+json</value></set-header>
            <set-header name="Accept" exists-action="override"><value>application/json</value></set-header>
            <set-body>@{{
                string v = context.Variables["{param_name}"] as string;
                return JsonConvert.SerializeObject(new {{
                    query = "SELECT * FROM c WHERE c.{field} = @{param_name}",
                    parameters = new object[] {{ new {{ name = "@{param_name}", value = v }} }}
                }});
            }}</set-body>
        </send-request>
        <choose>
            <when condition="@(((IResponse)context.Variables[&quot;cosmosResponse&quot;]).StatusCode == 200)">
                <return-response>
                    <set-status code="200" reason="OK" />
                    <set-header name="Content-Type" exists-action="override"><value>application/json</value></set-header>
                    <set-body>@{{
                        var response = ((IResponse)context.Variables["cosmosResponse"]).Body.As&lt;JObject&gt;();
                        var docs = response["Documents"] as JArray;
                        return docs.Count > 0 ? docs[0].ToString() : JsonConvert.SerializeObject(new {{ error = "not found" }});
                    }}</set-body>
                </return-response>
            </when>
            <otherwise>
                <return-response>
                    <set-status code="502" reason="Cosmos DB Query Failed" />
                    <set-header name="Content-Type" exists-action="override"><value>application/json</value></set-header>
                    <set-body>@{{ return ((IResponse)context.Variables["cosmosResponse"]).Body.As&lt;string&gt;(); }}</set-body>
                </return-response>
            </otherwise>
        </choose>
    </inbound>
    <backend><base /></backend>
    <outbound><base /></outbound>
    <on-error><base /></on-error>
</policies>"""

cred = AzureCliCredential()
client = ApiManagementClient(cred, sub_id)

def create_api(api_id, display_name, description, path):
    client.api.begin_create_or_update(rg, service, api_id,
        ApiCreateOrUpdateParameter(display_name=display_name, description=description,
            path=path, protocols=[Protocol.https], subscription_required=True)).result()

print("Creating Machine API...")
create_api("machine-api", "Machine API", "Machines via Cosmos DB (APIM MI)", "machine")

client.api_operation.create_or_update(rg, service, "machine-api", "list-machines",
    OperationContract(display_name="List Machines", description="List all machines",
        method="GET", url_template="/", template_parameters=[], responses=[ResponseContract(status_code=200, description="OK")]))
client.api_operation_policy.create_or_update(rg, service, "machine-api", "list-machines", "policy",
    parameters=PolicyContract(value=policy_query_all("Machines"), format="rawxml"))

client.api_operation.create_or_update(rg, service, "machine-api", "get-machine",
    OperationContract(display_name="Get Machine", description="Get machine by id",
        method="GET", url_template="/{id}",
        template_parameters=[ParameterContract(name="id", type="string", required=True)],
        responses=[ResponseContract(status_code=200, description="OK"), ResponseContract(status_code=404, description="Not Found")]))
client.api_operation_policy.create_or_update(rg, service, "machine-api", "get-machine", "policy",
    parameters=PolicyContract(value=policy_query_by_id("Machines", "id", "id"), format="rawxml"))
print("Machine API deployed!")

print("Creating Maintenance API...")
create_api("maintenance-api", "Maintenance API", "Thresholds via Cosmos DB (APIM MI)", "maintenance")

client.api_operation.create_or_update(rg, service, "maintenance-api", "list-thresholds",
    OperationContract(display_name="List Thresholds", description="List all thresholds",
        method="GET", url_template="/", template_parameters=[], responses=[ResponseContract(status_code=200, description="OK")]))
client.api_operation_policy.create_or_update(rg, service, "maintenance-api", "list-thresholds", "policy",
    parameters=PolicyContract(value=policy_query_all("Thresholds"), format="rawxml"))

client.api_operation.create_or_update(rg, service, "maintenance-api", "get-threshold",
    OperationContract(display_name="Get Threshold", description="Get threshold by machine type",
        method="GET", url_template="/{machineType}",
        template_parameters=[ParameterContract(name="machineType", type="string", required=True)],
        responses=[ResponseContract(status_code=200, description="OK"), ResponseContract(status_code=404, description="Not Found")]))
client.api_operation_policy.create_or_update(rg, service, "maintenance-api", "get-threshold", "policy",
    parameters=PolicyContract(value=policy_query_by_id("Thresholds", "machineType", "machineType"), format="rawxml"))
print("Maintenance API deployed!")
'@ | Set-Content -Path $seedApimPy -Encoding UTF8

Write-Host "Running APIM setup..."
Push-Location $Challenge0
python $seedApimPy
Pop-Location
Remove-Item $seedApimPy -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "All seeding complete!" -ForegroundColor Green
